---
- hosts: webserver
  remote_user: aitor
  tasks: 
    - name: Install last version of NGINX
      apt: name=nginx state=latest
      become: yes
    - name: Start/Enable
      service:
       name: nginx
       state: started
       enabled: yes
      become: yes
